import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";
import { ClientRoot } from "./client-root";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jira clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased min-h-screen")}>
        <ClientRoot>{ children }</ClientRoot>
      </body>
    </html>
  );
}
